[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
amm_video = "7sMZ4Mcfu31WW9fb4F68skkfsUYLcPAkJBiauoZXXbVC"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
